app/urls.py
from django.urls import path, re_path   
from django.contrib.auth import views as auth_views
from .views import home, servicio, registro, consulta, informe,registroPC,\
registroET,registroAM,registroAE,consultaVM,consultaInfoM,consultaIC,salir,\
buscar,consulta_registro_vm, modificar_formulario,modificar_formulario1,\
modificar_formulario2, modificar_formulario3,eliminar_formulario, eliminar_formulario1,\
eliminar_formulario2, eliminar_formulario3,NotFoundView


urlpatterns = [
    path('', home, name="home"),
    path('servicio/', servicio, name="servicio"),
    path('registro/', registro, name="registro"),
    path('consulta/', consulta, name="consulta"),
    path('informe/', informe, name="informe"),
    path('registroPC/', registroPC, name="registroPC"),
    path('registroET/', registroET, name="registroET"),
    path('registroAM/', registroAM, name="registroAM"),
    path('registroAE/', registroAE, name="registroAE"),
    path('consultaVM/', consultaVM, name="consultaVM"),
    path('consultaInfoM/', consultaInfoM, name="consultaInfoM"),
    path('consultaIC/', consultaIC, name="consultaIC"),
    path('salir/', salir, name='salir'),
    path('buscar/', buscar, name='buscar'), # type: ignore
    path('consulta_vm/', consulta_registro_vm, name='consulta_registro_vm'),
    path('modificar_formulario/<id>/', modificar_formulario, name="modificar_formulario"),
    path('modificar_formulario1/<id>/', modificar_formulario1, name="modificar_formulario1"),
    path('modificar_formulario2/<id>/', modificar_formulario2, name="modificar_formulario2"),
    path('modificar_formulario3/<id>/', modificar_formulario3, name="modificar_formulario3"),
    path('eliminar_formulario/<id>/', eliminar_formulario, name = "eliminar_formulario"),
    path('eliminar_formulario1/<id>/', eliminar_formulario1, name = "eliminar_formulario1"),
    path('eliminar_formulario2/<id>/', eliminar_formulario2, name = "eliminar_formulario2"),
    path('eliminar_formulario3/<id>/', eliminar_formulario3, name = "eliminar_formulario3"),

]

urlpatterns += [
    re_path(r'^.*/$', NotFoundView.as_view(), name='not_found'),
]

safe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class regCapacitacion(models.Model):
    METODOLOGIA_CHOICES = [
        ('Presentaciones', 'Presentaciones'),
        ('Demostraciones', 'Demostraciones'),
        ('Ejercicios', 'Ejercicios Practicos'),
        ('Preguntas', 'Preguntas'),
    ]

    id = models.AutoField(primary_key=True)
    nombre_completo = models.CharField(max_length=100)
    email = models.CharField(max_length=100 )
    nombre_curso = models.CharField(max_length=100)
    fecha_curso = models.DateField()
    genero = models.CharField(max_length=10, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')])
    ubicacion_curso = models.CharField(max_length=100) 
    encargado_curso = models.CharField(max_length=100)
    metodologia_ensenanza = models.CharField(max_length=100, choices=METODOLOGIA_CHOICES, default='Presentaciones')
    ciudad = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    codigo_postal = models.IntegerField()

    def __str__(self):
        return self.nombre_curso
    

    
class regMedico(models.Model):
    SERVICIO_CHOICES = [
        ('Cardiologo', 'Cardiologo'),
        ('Odontologia', 'Odontologia'),
        ('Medicina General', 'Medicina General'),
        ('Traumatologia', 'Traumatologia'),
        ('Psicologia','Psicologia'),
        ('Dermatologia','Dermatologia')
    ]

    id = models.AutoField(primary_key=True)
    nombre_completoM = models.CharField(max_length=100)
    rutM = models.CharField(max_length=100 )
    nombre_medicoM = models.CharField(max_length=100)
    fecha_atencionM = models.DateField()
    genero1 = models.CharField(max_length=10, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')])
    previsionM = models.CharField(max_length=100) 
    ocupacionM = models.CharField(max_length=100)
    servicio_atencionM = models.CharField(max_length=100, choices=SERVICIO_CHOICES, default='Cardiologo')
    historialM = models.CharField(max_length=80)
    alergiaM = models.CharField(max_length=50)
    fecha_proxM = models.DateField()

    def __str__(self):
        return self.rutM
    

class regExamen(models.Model):
    SERVICIO_CHOICES = [
        ('Cardiologo', 'Cardiologo'),
        ('Odontologia', 'Odontologia'),
        ('Medicina General', 'Medicina General'),
        ('Traumatologia', 'Traumatologia'),
        ('Psicologia','Psicologia'),
        ('Dermatologia','Dermatologia')
    ]

    id = models.AutoField(primary_key=True)
    nombre_completoE = models.CharField(max_length=100, null=False ,default='')
    rutE = models.CharField(max_length=100, null=False )
    nombre_medicoE = models.CharField(max_length=100)
    fecha_examenE = models.DateField()
    generoE = models.CharField(max_length=10, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')])
    resultadoE = models.CharField(max_length=100) 
    observacionE = models.CharField(max_length=100)
    servicio_atencionE = models.CharField(max_length=100, choices=SERVICIO_CHOICES, default='Cardiologo')
    historialE = models.CharField(max_length=80)
    tratamientoE = models.CharField(max_length=50)
    fecha_proxE = models.DateField()

    def __str__(self):
        return self.rutE
    


class regTerreno(models.Model):
    SERVICIO_CHOICES = [
        ('Subterraneo', 'Subterraneo'),
        ('Superficie', 'Superficie'),
        ('Cantera', 'Cantera'),
        ('Montaña', 'Montaña'),
        
    ]

    id = models.AutoField(primary_key=True)
    nombre_terreno = models.CharField(max_length=100)
    ubicacion_terreno = models.CharField(max_length=100 )
    topografia = models.CharField(max_length=100)
    fecha_registro = models.DateField()
    riesgo1 = models.CharField(max_length=10, choices=[('Si', 'Si'), ('No', 'No')])
    clima = models.CharField(max_length=100) 
    obsevacionT = models.CharField(max_length=100)
    tipo_terreno = models.CharField(max_length=100, choices=SERVICIO_CHOICES, default='Subterraneo')
    deteccionQuimico = models.CharField(max_length=80)
    materialUt = models.CharField(max_length=50)
    salidas = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nombre_terreno
    
class Contacto (models.Model):
    nombre = models.CharField(max_length=50)
    email = models.EmailField()
    numero = models.IntegerField()
    asunto = models.CharField(max_length=50)
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %} 

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Safe</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css" />
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <!-- Agrega esto en la sección head de tu HTML -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-r/A1aBd2x0I2VdTrTasIjXYxKcSsxDfFWCV4wF/Yqz4ZMxyNKqCXSbR72HPWiMH3" crossorigin="anonymous">



</head>
<body>
      <!--Navbar Inicio-->
 
      <header class="header">
        <a href="{% url 'home' %}" class="logo"><img src="{% static 'app/img/logo.png' %}" alt="" class="logo"></a>
        <i class='bx bx-menu' id="menu-icon"></i>
        <nav class="navbar">
            <a href="{% url 'home' %}">Inicio</a>
            <a href="#card">Nosotros</a>
            {% if user.is_authenticated  %}

            <a href="{% url 'servicio' %}">Servicios</a>
            {% endif %}
            <a href="#contact">Contacto</a>
            {% if user.is_authenticated  %}
            <a href="{% url 'salir' %}">Cerrar Sesión</a>
            <a href="#"><i class="fa-solid fa-user"></i>  {{ user.username }}</a>
            {% else %}
            <a href="{% url 'login' %}">Inicio Sesión</a>
            {% endif %}  
        </nav>
    </header>
    <div class="nav-bg"></div>
    <!--Navbar fin-->



    <div class="contenido">

        {% block contenido %}
        {% endblock %}
    </div>





    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col">
                    <h4>Compañia</h4>
                    <ul>
                        <li><a href="#card" >Sobre Nosotros</a></li>
                        <li><a href="#">Nuestros Servicios</a></li>
                        <li><a href="#">Politica</a></li>
                        <li><a href="#">Programas afiliados</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Obten Ayuda</h4>
                    <ul>
                        <li><a href="#">Contacto</a></li>
                        <li><a href="#">Foro</a></li>
                        <li><a href="#">Atenciones</a></li>
                        <li><a href="#">Opciones De Pago</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Datos</h4>
                    
                    <p class="textop">Contacto: safePrv@gmail.com</p>
                    <p class="textop">Dirección: Froilan Roa 6543, La Florida, RM</p>
                    <p class="textop">Número de Telefono: +56 9 8452 4856</p>
                    
                </div>
                <div class="footer-col">
                    <h4>Siguenos</h4>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="texto">
            <p>© 2023 Safe Prevención de Riesgos</p>
        </div>
   </footer>

   <script src="{% static 'app/js/script.js' %}"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

app/templates/app/consultaInfoM.html
{% extends 'app/base.html' %}

{% load static %}

{% block contenido %}


<body class="consultavm">
    


    <div class="container-consulta">
        <img src="{% static 'app/img/medico3.jpg' %}" alt="" class="medico3">
        
        <section class="heor">
            <div class="heading">
                <h2>Consultas De Información Medica</h2>
            </div>
            <div class="container-medicina">
                <div class="hero-image">
                    <img class="imgMedicina" src="{% static 'app/img/18240.jpg' %}" alt="">
                </div>
                <div class="hero-content">
                    <h3>Ingrese su Rut o nombre para buscar su registro</h3>
                    <p>En esta sección, te ofrecemos una experiencia de búsqueda de
                         consultas de información medica optimizada y personalizada.
                          Nuestra plataforma te permite explorar una amplia 
                          y detallada información sobre tus examenes medicos, especializados en 
                          diversas áreas médicas, como Cardiologia, Dermatologia, Traumatologia, etc.
                          Nos enorgullecemos de brindar un entorno seguro y confidencial 
                          para tus necesidades de salud. Todas las consultas se realizan 
                          de manera virtual o presencial, según tu elección. 
                          La comunicación fluida entre pacientes y profesionales es 
                          fundamental para nosotros, y estamos comprometidos a garantizar
                          que cada encuentro sea satisfactorio y esclarecedor.
                    </p>
                    <center><button class="botonI" onclick="redirigirAOtraURL()">Inicio</button></center>
                  
                </div>
    
    
                
    
            </div>
           
    
        </section>
        
        
    </div>
    
    
    <div class="botonBusc" style="margin-bottom: 200px;">
        <form method="get" action="{% url 'consultaInfoM' %}" >
            <div class="search-box" style="background-color: rgb(27, 98, 231);">
              <div class="input-box1" style="color: black;">
                <i class='bx bx-search'></i>
                <input type="text" type="submit" placeholder="Buscar... " name="registro_id">
              </div>
            </div>
            </form>
        </div>
    
    
        {% if registro %}
        <div class="contenedor-informe">
            <h1 class="tituloInf">Informes de Examenes</h1>
                <table class="content-table">
                    <thead>
                        <tr>
                            <th>Nombre Completo Paciente</th>
                            <th>RUT Paciente</th>
                            <th>Nombre del Medico</th>
                            <th>Fecha del Examen</th>
                            <th>Género</th>
                            <th>Resultados</th>
                            <th>Observaciones</th>
                            <th>Servicio de Atención</th>
                            <th>Historial Medico</th>
                            <th>Tratamiento Recomendado</th>
                            <th>Siguiente Atención</th>
                          
                        
                        </tr>
                    </thead>
                    <tbody class="active-row">
                            <tr>
                                <td>{{ registro.nombre_completoE }}</td>
                                <td>{{ registro.rutE }}</td>
                                <td>{{ registro.nombre_medicoE }}</td>
                                <td>{{ registro.fecha_examenE }}</td>
                                <td>{{ registro.generoE }}</td>
                                <td>{{ registro.resultadoE }}</td>
                                <td>{{ registro.observacionE }}</td>
                                <td>{{ registro.servicio_atencionE }}</td>
                                <td>{{ registro.historialE }}</td>
                                <td>{{ registro.tratamientoE }}</td>
                                <td>{{ registro.fecha_proxE }}</td>
                            
                            </tr>
                        
                    </tbody>
                </table>
        
            </div>
    {% endif %}
    
    </body>
 
    <script>
        function redirigirAOtraURL() {
            window.location.href = "{% url 'home' %}";
        }
    </script>    

{% endblock %}

app/templates/app/informe.html
{% extends 'app/base.html' %}

{% load static %}

{% block contenido %}
{% load humanize %}
<body class="informes">
    
    <div class="botonBusc">
    <form method="get" action="{% url 'buscar' %}" >
        <div class="search-box">
          <div class="input-box1">
            <i class='bx bx-search'></i>
            <input type="text" type="submit" placeholder="Buscar... " name="buscar">
          </div>
        </div>
        </form>
    </div>

<div class="containerInf">
    <div class="contenedor-informe">
        {% if perms.app.view_regcapacitacion %}

    <h1 class="tituloInf">Informes de Capacitación</h1>
        <table class="content-table">
            <thead>
                <tr>
                    <th>Nombre Completo</th>
                    <th>Email</th>
                    <th>Nombre del Curso</th>
                    <th>Fecha del Curso</th>
                    <th>Género</th>
                    <th>Ubicación del Curso</th>
                    <th>Encargado del Curso</th>
                    <th>Metodología de Enseñanza</th>
                    <th>Ciudad</th>
                    <th>Región</th>
                    <th>Código Postal</th>
                    <th>Editar</th>
                    <th>Borrar</th>
                
                </tr>
            </thead>
            <tbody class="active-row">
                {% for c in capacitaciones %}
                    <tr>
                        <td>{{ c.nombre_completo }}</td>
                        <td>{{ c.email }}</td>
                        <td>{{ c.nombre_curso }}</td>
                        <td>{{ c.fecha_curso }}</td>
                        <td>{{ c.genero }}</td>
                        <td>{{ c.ubicacion_curso }}</td>
                        <td>{{ c.encargado_curso }}</td>
                        <td>{{ c.metodologia_ensenanza }}</td>
                        <td>{{ c.ciudad }}</td>
                        <td>{{ c.region }}</td>
                        <td>{{ c.codigo_postal }}</td>
                        {% if perms.app.change_regcapacitacion %}
                        <td><a href="{% url 'modificar_formulario' c.id%}" class="btn btn-info btn-sm">Modificar</a></td>
                        {% endif %}
                        {% if perms.app.delete_regcapacitacion %}
                        <td><a href="{% url 'eliminar_formulario' c.id%}" class="btn btn-danger btn-sm">Eliminar</a></td>
                        {% endif %}
                     
                    </tr>
                    {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>

    <br><br>

    <div class="contenedor-informe">
        {% if perms.app.view_regmedico %}
        <h1 class="tituloInf">Informes de Atenciones Medicas</h1>
            <table class="content-table">
                <thead>
                    <tr>
                        <th>Nombre Completo Paciente</th>
                        <th>RUT Paciente</th>
                        <th>Nombre del Medico</th>
                        <th>Fecha Atención Medica</th>
                        <th>Género</th>
                        <th>Previsión del Paciente</th>
                        <th>Ocupación del Paciente</th>
                        <th>Servicio de Atención</th>
                        <th>Historial Medico</th>
                        <th>Alergias</th>
                        <th>Siguiente Atención</th>
                        <th>Editar</th>
                        <th>Borrar</th>
                    
                    </tr>
                </thead>
                <tbody class="active-row">
                    {% for m in atenciones %}
                        <tr>
                            <td>{{ m.nombre_completoM }}</td>
                            <td>{{ m.rutM }}</td>
                            <td>{{ m.nombre_medicoM }}</td>
                            <td>{{ m.fecha_atencionM }}</td>
                            <td>{{ m.genero1 }}</td>
                            <td>{{ m.previsionM }}</td>
                            <td>{{ m.ocupacionM }}</td>
                            <td>{{ m.servicio_atencionM }}</td>
                            <td>{{ m.historialM }}</td>
                            <td>{{ m.alergiaM }}</td>
                            <td>{{ m.fecha_proxM }}</td>
                            {% if perms.app.change_regmedico %}
                            <td><a href="{% url 'modificar_formulario1' m.id%}" class="btn btn-info btn-sm">Modificar</a></td>
                            {% endif %}
                            {% if perms.app.delete_regmedico %}
                            <td><a href="{% url 'eliminar_formulario1' m.id%}" class="btn btn-danger btn-sm">Eliminar</a></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>

        <br><br>

        <div class="contenedor-informe">
            {% if perms.app.view_regexamen %}
            <h1 class="tituloInf">Informes de Examenes</h1>
                <table class="content-table">
                    <thead>
                        <tr>
                            <th>Nombre Completo Paciente</th>
                            <th>RUT Paciente</th>
                            <th>Nombre del Medico</th>
                            <th>Fecha del Examen</th>
                            <th>Género</th>
                            <th>Resultados</th>
                            <th>Observaciones</th>
                            <th>Servicio de Atención</th>
                            <th>Historial Medico</th>
                            <th>Tratamiento Recomendado</th>
                            <th>Siguiente Atención</th>
                            <th>Editar</th>
                            <th>Borrar</th>
                        
                        </tr>
                    </thead>
                    <tbody class="active-row">
                        {% for e in examenes %}
                            <tr>
                                <td>{{ e.nombre_completoE }}</td>
                                <td>{{ e.rutE }}</td>
                                <td>{{ e.nombre_medicoE }}</td>
                                <td>{{ e.fecha_examenE }}</td>
                                <td>{{ e.generoE }}</td>
                                <td>{{ e.resultadoE }}</td>
                                <td>{{ e.observacionE }}</td>
                                <td>{{ e.servicio_atencionE }}</td>
                                <td>{{ e.historialE }}</td>
                                <td>{{ e.tratamientoE }}</td>
                                <td>{{ e.fecha_proxE }}</td>
                                {% if perms.app.change_regexamen %}
                                <td><a href="{% url 'modificar_formulario2' e.id%}" class="btn btn-info btn-sm">Modificar</a></td>
                                {% endif %}
                                {% if perms.app.delete_regexamen %}
                                <td><a href="{% url 'eliminar_formulario2' e.id%}" class="btn btn-danger btn-sm">Eliminar</a></td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            </div>


            <br><br>

            <div class="contenedor-informe">
                {% if perms.app.view_regterreno %}
                <h1 class="tituloInf">Informes de Terrenos</h1>
                    <table class="content-table">
                        <thead>
                            <tr>
                                <th>Nombre del Terreno</th>
                                <th>Ubicación del terreno</th>
                                <th>Topografía</th>
                                <th>Fecha del Registro</th>
                                <th>Riesgos</th>
                                <th>Clima del terreno</th>
                                <th>Observaciones</th>
                                <th>Tipos de terrenos</th>
                                <th>Sustancias Peligrosas</th>
                                <th>Material Utilizado</th>
                                <th>Salidas de Emergencia</th>
                                <th>Editar</th>
                                <th>Borrar</th>
                            
                            </tr>
                        </thead>
                        <tbody class="active-row">
                            {% for t in terrenos %}
                                <tr>
                                    <td>{{ t.nombre_terreno }}</td>
                                    <td>{{ t.ubicacion_terreno }}</td>
                                    <td>{{ t.topografia }}</td>
                                    <td>{{ t.fecha_registro }}</td>
                                    <td>{{ t.riesgo1 }}</td>
                                    <td>{{ t.clima }}</td>
                                    <td>{{ t.obsevacionT }}</td>
                                    <td>{{ t.tipo_terreno }}</td>
                                    <td>{{ t.historialE }}</td>
                                    <td>{{ t.materialUt }}</td>
                                    <td>{{ t.salidas }}</td>
                                    {% if perms.app.change_regterreno %}
                                    <td><a href="{% url 'modificar_formulario3' t.id%}" class="btn btn-info btn-sm">Modificar</a></td>
                                    {% endif %}
                                    {% if perms.app.delete_regterreno %}
                                    <td><a href="{% url 'eliminar_formulario3' t.id%}" class="btn btn-danger btn-sm">Eliminar</a></td>
                                    {% endif %}
                                </tr>
                                {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}
            
                </div>
</div>
</body>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-r/A1aBd2x0I2VdTrTasIjXYxKcSsxDfFWCV4wF/Yqz4ZMxyNKqCXSbR72HPWiMH3" crossorigin="anonymous">

<style>
    .expand-icon::before,
    .collapse-icon::before {
        content: '\f078'; /* Código del icono de flecha hacia abajo de Font Awesome */
        cursor: pointer;
        display: inline-block;
        float: right;
        margin-left: 10px;
        font-family: 'Font Awesome 5 Free';
        font-weight: 900;
    }

    .collapse-icon::before {
        content: '\f077'; /* Código del icono de flecha hacia arriba de Font Awesome */
    }

    .contenedor-informe h1 {
        clear: both;
    }
</style>

<script>
    $(document).ready(function () {
        // Ocultar todas las tablas al principio
        $(".content-table").hide();

        // Añadir un ícono a los encabezados
        $(".contenedor-informe h1").prepend('<span class="expand-icon"></span>');

        // Manejar el evento de clic en los encabezados para colapsar/expandir
        $(".contenedor-informe h1").click(function () {
            var table = $(this).next(".content-table");
            $(".content-table").not(table).hide(); // Ocultar otras tablas
            table.toggle();

            // Cambiar el ícono según si la tabla está visible o no
            $(".contenedor-informe h1 span").removeClass("collapse-icon").addClass("expand-icon");
            if (table.is(":visible")) {
                $(this).find("span").removeClass("expand-icon").addClass("collapse-icon");
            } else {
                $(this).find("span").removeClass("collapse-icon").addClass("expand-icon");
            }
        });
    });
</script>

{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}

{% load static %}

{% block contenido %}


<body class="loginBody">
    


<div class="contenidologin">

<div class="wrapper login-w">
    <div class="form-box login" >
        <h2 class="text-login">Ingresar</h2>
        <form action="#" method="POST">
            {% csrf_token %} 
            <div class="input-box">
                <span class="icon"><ion-icon name="mail"></ion-icon></span>
                <input type="tex" name="username" required>
                <label for="">usuario</label>
            </div>
            <div class="input-box">
                <span class="icon"><ion-icon name="lock-closed"></ion-icon></span>
                <input type="password" name="password" required>
                <label for="">Contraseña</label>
            </div>
            <div class="remember-forgot">
                <label for="" class="textologin"><input type="checkbox">Recordarme</label>
                <a class="forget-pass" href="#">Olvidaste tu Contraseña</a>
            </div>
            <button type="submit" class="btn-login">Ingresar</button>
            <div class="login-register">
                <p class="textologin">¿No tienes una cuenta?<a 
            
                    href="{% url 'registro' %}" class="register-link"> Registrar</a></p>
            </div>
        </form>
    </div>
</div>

</div>
</body>

{% endblock %}

app/templates/app/modificar.html
{% extends 'app/base.html' %}

{% load static %}

{% block contenido %}
<br><br>
<h1>Editar Formularios</h1>
<!-- modificar.html -->
<div class="contenedorPC">
  <div class="containerPC">
      <h1 class="tituloF">Modificar Plan de Capacitación</h1>
      <hr class="hr">
      <form method="post" class="formPC">
          {% csrf_token %}

          <div class="input-box">
              {{ form.nombre_completo }}
          </div>
          <div class="input-box">
              {{ form.email }}
          </div>
          <div class="column">
              <div class="input-box">
                  {{ form.nombre_curso }}
              </div>
              <div class="input-box">
                  <label class="fechaL">Fecha del curso</label>
                  {{ form.fecha_curso }}
              </div>
          </div>
          <div class="gender-box">
              <h3>Genero</h3>
              <div class="gender-option">
                  <div class="gender">
                      {{ form.genero }}
                  </div>
              </div>
          </div>
          <div class="input-box address">
              {{ form.ubicacion_curso }}
              {{ form.encargado_curso }}
              <div class="column">
                  <div class="select-box">
                      {{ form.metodologia_ensenanza }}
                  </div>
                  {{ form.ciudad }}
              </div>
              <div class="column">
                  {{ form.region }}
                  {{ form.codigo_postal }}
              </div>
              <button type="submit">Guardar cambios</button>
          </div>
      </form>
  </div>
</div>



{% endblock %}